apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datadog-sql-metrics.fullname" . }}
  labels:
    {{- include "datadog-sql-metrics.labels" . | nindent 4 }}
data:
  setup: |
    mkdir -p /output/{{ .Values.database.type }}.d
    sed "s/DB_USERNAME/$DB_USERNAME/g" /input/config.yaml | sed "s/DB_PASSWORD/$DB_PASSWORD/g" > /output/{{ .Values.database.type }}.d/config.yaml
  config.yaml: |
    {{- with .Values.database.config }}
      {{- toYaml . | nindent 4 }}
    {{- end }}

